export * from 'tamagui';
export * from '@tamagui/toast';
export * from './MyComponent';
export { config } from '@my/config';
export * from './CustomToast';
export * from './SwitchThemeButton';
export * from './SwitchRouterButton';
export { WebButton } from './Button/WebButton';
export { Heading as WebHeading } from './Heading/Heading';
export { Input as WebInput } from './Input/Input';
export { LucideIcon as WebLucideIcon } from './LucideIcon/LucideIcon';
export { Checkbox as WebCheckbox } from './Checkbox/Checkbox';
export { TextArea as WebTextArea } from './TextArea/TextArea';
export { Label as WebLabel } from './Label/Label';
